[[main]]
  name = "About"
  pageRef = "about"
  weight = 10


[[main]]
  name = "Anchor"
  pageRef = "anchor"
  weight = 12

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20

[[main]]
  name = "Careers"
  pageRef = "careers"
  weight = 25

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 30

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"
